{% set name = "apache-airflow-providers-apache-spark" %}
{% set version = "4.11.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/apache_airflow_providers_apache_spark-{{ version }}.tar.gz
  sha256: 3e7841a0a2d2e0b27dba35d31deabf5191ce58ac0e2bc6335cb29875aa65d841

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv  --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9,<4.dev0
    - flit-core >=3.2,<4
    - pip
  run:
    - python >=3.9,<4.dev0
    - apache-airflow >=2.8.0
    - grpcio-status >=1.59.0
    - pyspark >=3.1.3

test:
  imports:
    - airflow.providers.apache.spark
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/apache/airflow/
  summary: Provider package apache-airflow-providers-apache-spark for Apache Airflow
  license: Apache-2.0
  license_file: airflow/providers/apache/spark/LICENSE
  license_family: Apache
  doc_url: https://airflow.apache.org/docs/apache-airflow-providers-apache-spark/stable/index.html
  dev_url: https://github.com/apache/airflow/

extra:
  recipe-maintainers:
    - xylar
