{% set name = "apache-airflow-providers-apache-spark" %}
{% set version = "4.11.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/apache_airflow_providers_apache_spark-{{ version }}.tar.gz
  sha256: 77e98cb33c3ca371165274e75e5133349c9b8292423db14e740b259e3eaf3afc

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv  --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - flit-core ==3.10.1
    - pip
  run:
    - python >={{ python_min }}
    - apache-airflow >=2.8.0
    - grpcio-status >=1.59.0
    - pyspark >=3.1.3

test:
  imports:
    - airflow.providers.apache.spark
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/apache/airflow/
  summary: Provider package apache-airflow-providers-apache-spark for Apache Airflow
  license: Apache-2.0
  license_file: airflow/providers/apache/spark/LICENSE
  license_family: Apache
  doc_url: https://airflow.apache.org/docs/apache-airflow-providers-apache-spark/stable/index.html
  dev_url: https://github.com/apache/airflow/

extra:
  recipe-maintainers:
    - xylar
